---
kind: pipeline
name: test-and-publish

clone:
  git:
    image: plugins/git
    # include tags when cloning for version calc
    tags: true

steps:
  - name: check-cache-dir
    image: alpine:latest
    commands:
      - echo ${DRONE_MACHINE}
      - mkdir -p /tmp/gradle/wrapper
      - mkdir -p /tmp/gradle/cache/modules-2
    volumes:
      - name: host-tmp
        path: /tmp

  - name: unit-test
    image: openjdk:8-jdk-slim
    environment:
      GRADLE_USER_HOME: /gradle/
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
    volumes:
      - name: gradle-wrappers
        path: /gradle/wrapper
      - name: gradle-modules-2
        path: /gradle/caches/modules-2
    commands:
      # TODO(GB): Enable checkstyle
      #- ./gradlew compileJava test check
      - ./gradlew compileJava test

  - name: publish-to-s3
    image: openjdk:8-jdk
    environment:
      GRADLE_USER_HOME: /gradle/
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
      AWS_ACCESS_KEY_ID:
        from_secret: aws-publish-id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws-publish-secret
    volumes:
      - name: gradle-wrappers
        path: /gradle/wrapper
      - name: gradle-modules-2
        path: /gradle/caches/modules-2
    commands:
      - ./gradlew --info publish -x check -x test
    when:
      branch:
        include:
          - master

volumes:
  - name: host-tmp
    host:
      path: /tmp
  - name: gradle-wrapper
    host:
      path: /tmp/gradle/wrapper
  - name: gradle-modules-2
    host:
      path: /tmp/gradle/cache/modules-2

trigger:
  event:
    - push

---
kind: pipeline
name: mirror-to-github
depends_on:
  - test-and-publish

steps:
  - name: github-push
    image: alpine/git
    environment:
      GITHUB_SSH_KEY_B64:
        from_secret: github-ssh-key-b64
    commands:
      - ./mirror.sh
    when:
      branch:
        include:
          - master

trigger:
  event:
    - push

---
kind: secret
name: aws-publish-id
get:
  path: drone/publish/s3
  name: aws-publish-id

---
kind: secret
name: aws-publish-secret
get:
  path: drone/publish/s3
  name: aws-publish-secret

---
kind: secret
name: github-ssh-key-b64
get:
  path: drone/publish/github/inpro-jira
  name: gh-jira-key-b64
